name: Frontend Linting and Formatting Checks
on:
  workflow_call:

jobs:
  es-lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
        working-directory: frontend
      - run: pnpm run lint
        working-directory: frontend

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
        working-directory: frontend
      - run: pnpm run format:check
        working-directory: frontend
