services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    volumes:
      -  ~/myvote/db:/app
    environment:
      - UV_COMPILE_BYTECODE=1

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
