services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    volumes:
      - .:/app
    environment:
      - UV_COMPILE_BYTECODE=1
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  database:
    image: sqlite:latest
    volumes:
      - ./backend/dump.sql:/data/dump.sql
    restart: always
