"""init

Revision ID: 9d60935937c6
Revises:
Create Date: 2025-01-01 01:46:36.876790

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d60935937c6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "election",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nomination_start", sa.DateTime(), nullable=False),
        sa.Column("nomination_end", sa.DateTime(), nullable=False),
        sa.Column("voting_start", sa.DateTime(), nullable=False),
        sa.Column("voting_end", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PreRelease",
                "Nominations",
                "NominationsClosed",
                "Voting",
                "VotingClosed",
                "ResultsReleased",
                name="electionstatus",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("statement", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["election"],
            ["election.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vacancies", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("executive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["election"],
            ["election.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "voter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("election", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["election"],
            ["election.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ballot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voter_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("submitted", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position"],
            ["position.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["voter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidatepositionlink",
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id", "position_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidatepositionlink")
    op.drop_table("ballot")
    op.drop_table("voter")
    op.drop_table("position")
    op.drop_table("candidate")
    op.drop_table("election")
    # ### end Alembic commands ###
