name: Backend Checks
on:
  workflow_call:

jobs:
  lint_and_format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "backend/uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv sync
        working-directory: backend

      - name: Check for code errors
        run: |
          uv run ruff check
        working-directory: backend

      - name: Check formatting
        run: |
          uv run ruff format --check
        working-directory: backend
