name: Linting and Formatting Checks
on:
  workflow_call:

jobs:
  frontend:
    name: Frontend Checks
    uses: ./.github/workflows/frontend.yml

  backend:
    name: Backend Checks
    uses: ./.github/workflows/backend.yml
